FROM {{ item.image }}
RUN if command -v apt-get >/dev/null; then \
      apt-get update && apt-get install -y --no-install-recommends systemd systemd-sysv python3 sudo udev && apt-get clean; \
    else \
      dnf -y install systemd python3 sudo systemd-udev && dnf clean all; \
    fi
