"""direwolf.conf for the emcomm-direwolf user service (fully managed)."""

from __future__ import annotations

from ..models import ax25_callsign
from .context import RIGCTLD_ADDR, RenderContext

AGW_EXPOSURE_WARNING = (
    "warning: Dire Wolf's AGW port 8000 listens on all interfaces without authentication; "
    "block TCP 8000 on untrusted networks."
)


def render_direwolf(existing: str | None, ctx: RenderContext) -> str | None:
    if not ctx.alsa_device:
        return None
    lines = [
        "# Managed by emcomm: regenerated by `emcomm use`. Change profiles instead of this file.",
        f"ADEVICE plughw:CARD={ctx.station.alsa_id},DEV=0",
        "ACHANNELS 1",
        "CHANNEL 0",
        f"MYCALL {ax25_callsign(ctx.operator.callsign)}",
        "MODEM 1200",
    ]
    if ctx.ptt != "vox":
        lines.append(f"PTT RIG 2 {RIGCTLD_ADDR}")
    # Pat talks AGW on 8000. Dire Wolf has no bind-address option (1.8.1 listens on all
    # interfaces), so keep exposure minimal: KISSPORT 0 turns the KISS TCP listener off.
    lines += ["AGWPORT 8000", "KISSPORT 0"]
    return "\n".join(lines) + "\n"
