"""direwolf.conf for the emcomm-direwolf user service (fully managed)."""

from __future__ import annotations

from ..models import ax25_callsign
from .context import RIGCTLD_ADDR, RenderContext


def render_direwolf(existing: str | None, ctx: RenderContext) -> str | None:
    if not ctx.alsa_device:
        return None
    lines = [
        "# Managed by emcomm: regenerated by `emcomm use`. Change profiles instead of this file.",
        f"ADEVICE plughw:CARD={ctx.station.alsa_id},DEV=0",
        "ACHANNELS 1",
        "CHANNEL 0",
        f"MYCALL {ax25_callsign(ctx.operator.callsign)}",
        "MODEM 1200",
    ]
    if ctx.ptt != "vox":
        lines.append(f"PTT RIG 2 {RIGCTLD_ADDR}")
    lines += ["AGWPORT 8000", "KISSPORT 8001"]
    return "\n".join(lines) + "\n"
