"""Arguments for the rigctld hub (emcomm-rigctld.service EnvironmentFile)."""

from __future__ import annotations

from .context import RenderContext

DUMMY_MODEL = 1

# Characters that would break systemd EnvironmentFile word-splitting
FORBIDDEN_CHARS = {' ', '"', '\\', '$', '\n'}


def _validate_arg(arg: str) -> None:
    """Reject arguments containing characters that break systemd EnvironmentFile parsing."""
    for char in FORBIDDEN_CHARS:
        if char in arg:
            raise ValueError(
                f"argument contains forbidden character {char!r}: {arg!r}"
            )


def rigctld_args(ctx: RenderContext) -> list[str]:
    args = ["-m", str(ctx.radio.hamlib_model), "-T", "127.0.0.1", "-t", "4532"]
    has_cat = ctx.station.cat is not None
    if ctx.radio.hamlib_model != DUMMY_MODEL and has_cat:
        args += ["-r", ctx.station.cat_link, "-s", str(ctx.radio.baud)]
    if ctx.ptt in ("rts", "dtr") and has_cat:
        args += ["-P", ctx.ptt.upper(), "-p", ctx.station.cat_link]
    if ctx.radio.set_conf:
        args.append("--set-conf=" + ",".join(f"{k}={v}" for k, v in ctx.radio.set_conf))

    # Validate all arguments for dangerous characters
    for arg in args:
        _validate_arg(arg)

    return args


def render_rigctld(existing: str | None, ctx: RenderContext) -> str:
    return (
        "# Managed by emcomm: regenerated by `emcomm use`.\n"
        f'RIGCTLD_ARGS="{" ".join(rigctld_args(ctx))}"\n'
    )
