"""Arguments for the rigctld hub (emcomm-rigctld.service EnvironmentFile)."""

from __future__ import annotations

from .context import RIGCTLD_ADDR, RenderContext

DUMMY_MODEL = 1


def _validate_arg(arg: str) -> None:
    """Reject arguments containing whitespace or special chars that break systemd EnvironmentFile."""
    if any(ch.isspace() or ch in '"\\$' for ch in arg):
        raise ValueError(f"argument contains forbidden characters: {arg!r}")


def rigctld_args(ctx: RenderContext) -> list[str]:
    # Parse RIGCTLD_ADDR to extract host and port
    host, port = RIGCTLD_ADDR.split(":")

    args = ["-m", str(ctx.radio.hamlib_model), "-T", host, "-t", port]
    has_cat = ctx.station.cat is not None
    if ctx.radio.hamlib_model != DUMMY_MODEL and has_cat:
        args += ["-r", ctx.station.cat_link, "-s", str(ctx.radio.baud)]
    if ctx.ptt in ("rts", "dtr") and has_cat:
        args += ["-P", ctx.ptt.upper(), "-p", ctx.station.cat_link]
    if ctx.radio.set_conf:
        args.append("--set-conf=" + ",".join(f"{k}={v}" for k, v in ctx.radio.set_conf))

    # Validate all arguments for dangerous characters
    for arg in args:
        _validate_arg(arg)

    return args


def render_rigctld(existing: str | None, ctx: RenderContext) -> str:
    return (
        "# Managed by emcomm: regenerated by `emcomm use`.\n"
        f'RIGCTLD_ARGS="{" ".join(rigctld_args(ctx))}"\n'
    )
